CREATE TABLE IF NOT EXISTS live_probe_orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    market_slug TEXT,
    condition_id TEXT,
    token_id TEXT NOT NULL,
    side TEXT NOT NULL DEFAULT 'BUY',
    price REAL NOT NULL,
    size_shares REAL NOT NULL,
    order_id TEXT,
    post_ts_ms INTEGER,
    cancel_ts_ms INTEGER,
    status TEXT,
    filled_shares REAL DEFAULT 0,
    avg_fill_price REAL,
    resolved_side TEXT,
    pnl REAL,
    b_score REAL,
    b_ratio REAL,
    seconds_remaining REAL,
    queue_ahead_1c REAL,
    raw_post_response TEXT,
    raw_cancel_response TEXT
);
